version: '3.1'

services:
  wordpress:
    image: wordpress
    restart: always
    ports:
    - "8081:80"
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: user
      WORDPRESS_DB_PASSWORD: user123
      WORDPRESS_DB_NAME: db
    volumes:
      - wordpress:/var/www/html
    
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: db
      MYSQL_USER: user
      MYSQL_PASSWORD: user123
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - db:/var/lib/mysql
    
volumes:
  wordpress:
  db:

